name: Master build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Validate composer.json and composer.lock
        uses: php-actions/composer@40-env
        with:
          version: 2
          php_version: 7.4
          only_args: --prefer-dist --no-progress

      - name: Run phpunit tests
        uses: php-actions/phpunit@v8
        with:
          configuration: ./phpunit.xml
